project_id = "klhidaptujtjlqcxebnh"

[functions.reset-password]
verify_jwt = false

[functions.resolve-login-email]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.send-transaction-sms]
verify_jwt = false
